In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()

c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version: "+str(1000*(toc-tic))+"ms")

c=0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
    
toc = time.time()
print(c)
print("For loop: "+str(1000*(toc-tic))+" ms")

249956.75427139123
Vectorized version: 3.8585662841796875ms
249956.75427139123
For loop: 424.227237701416 ms


In [4]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = A.sum(axis = 0) # sum vertically
print(cal)

[ 59.  239.  155.4  76.9]


In [7]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [9]:
cal.reshape(1,4)

array([[ 59. , 239. , 155.4,  76.9]])

In [10]:
a = np.random.randn(5) #rank 1 arrays

print(a)

[-0.93666642 -1.98446438  0.47183322 -0.39714095  0.78940925]


In [11]:
print(a.shape)

(5,)


In [12]:
print(a.T)

[-0.93666642 -1.98446438  0.47183322 -0.39714095  0.78940925]


In [13]:
print(np.dot(a,a.T))

5.818957337091398


In [15]:
a = np.random.randn(5,1)

In [16]:
a

array([[ 0.1234104 ],
       [ 0.86922773],
       [-0.74751454],
       [-1.43254767],
       [-1.07908507]])

In [18]:
print(a.T)

[[ 0.1234104   0.86922773 -0.74751454 -1.43254767 -1.07908507]]


In [19]:
print(np.dot(a,a.T))

[[ 0.01523013  0.10727174 -0.09225107 -0.17679128 -0.13317032]
 [ 0.10727174  0.75555685 -0.64976037 -1.24521016 -0.93797067]
 [-0.09225107 -0.64976037  0.55877799  1.07085022  0.80663178]
 [-0.17679128 -1.24521016  1.07085022  2.05219283  1.5458408 ]
 [-0.13317032 -0.93797067  0.80663178  1.5458408   1.16442459]]


In [20]:
a = np.random.randn(4, 3) # a.shape = (4, 3)

In [21]:
print(a)

[[-0.88324196  0.62123875 -1.75741063]
 [ 0.3262668   0.53237039  0.97923902]
 [ 0.66624612  2.16771959  0.4950316 ]
 [-1.11504386  0.82307559  0.65969513]]


In [22]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [23]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [24]:
c

array([[ 2.17645654,  1.75583492,  2.33286758],
       [-0.32799763, -1.84807333, -0.49775958]])

In [25]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
c.shape

(12288, 45)

In [31]:
a = np.random.randn(3,4)
a

array([[ 0.81530984, -0.81111891,  0.84987702, -2.68697964],
       [-0.17944663,  1.43008497,  0.59083985,  2.46565783],
       [-1.09568355,  1.96946848, -0.70873962,  0.41310233]])

In [32]:
b = np.random.randn(4,1)
b

array([[-0.69476383],
       [ 1.26366816],
       [ 0.40834928],
       [ 0.88343329]])

In [35]:
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]

In [36]:
c

array([[  0.12054601,   0.45254925,   1.2582263 , ...,  16.35470552,
          1.90432263,   4.50608579],
       [ -0.87421047,   2.69375313,   0.99918912, ...,   6.69939735,
          7.56216169,  -4.15208367],
       [ -1.79044739,   3.23313664,  -0.30039034, ...,  40.96183816,
          1.99090704,  15.1631198 ],
       ...,
       [  0.69976802,   6.0287791 ,   6.36607262, ..., -13.05892461,
          9.16459036,  -2.12322136],
       [ -3.96389555,  -7.06119513,  -5.72922522, ...,  11.23659776,
         10.0742962 , -13.59899531],
       [  5.16522792,   9.97426933,   2.78815084, ...,   3.81256096,
         -1.53937182,  12.24166219]])

In [43]:
c = 0
c = a+b.T
c

array([[ 0.12054601,  0.45254925,  1.2582263 , -1.80354635],
       [-0.87421047,  2.69375313,  0.99918912,  3.34909112],
       [-1.79044739,  3.23313664, -0.30039034,  1.29653562]])

In [44]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[ 0.61395386,  1.0672625 , -2.56428683],
       [ 0.94856958, -0.2191978 ,  0.50809888],
       [-1.24624217,  0.9864221 ,  0.68917907]])

In [45]:
a

array([[ 0.37497747,  0.65183953, -1.5661597 ],
       [ 0.89718013, -0.2073226 ,  0.48057225],
       [ 0.92715462, -0.73385882, -0.51272183]])

In [46]:
b

array([[ 1.63730865],
       [ 1.05727886],
       [-1.34415786]])

In [47]:
c

array([[ 0.61395386,  1.0672625 , -2.56428683],
       [ 0.94856958, -0.2191978 ,  0.50809888],
       [-1.24624217,  0.9864221 ,  0.68917907]])

In [50]:
k = np.array([[2,3],[4,5]])
k

array([[2, 3],
       [4, 5]])

In [51]:
l = np.array([[1,0],[0,1]])

In [52]:
l

array([[1, 0],
       [0, 1]])

In [53]:
k*l

array([[2, 0],
       [0, 5]])