In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)


tensor([[ 1.1772e-04,  4.5881e-41,  1.1772e-04],
        [ 4.5881e-41,  1.8055e+17,  7.0072e+22],
        [ 1.8370e+25,  1.6577e+25,  1.0650e-32],
        [ 4.6149e+24,  1.8697e+25,  1.4603e-19],
        [ 1.8987e+28,  4.1363e+21,  1.8469e+25]])


In [3]:
x = torch.rand(5, 3)
print(x)


tensor([[ 0.4933,  0.8838,  0.7162],
        [ 0.7562,  0.3985,  0.5426],
        [ 0.4619,  0.7236,  0.0476],
        [ 0.4685,  0.5121,  0.3713],
        [ 0.9323,  0.1015,  0.6241]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)


tensor([ 5.5000,  3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size



tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[-1.2915, -1.8029,  0.9613],
        [ 0.7439, -0.6521, -0.2125],
        [-0.3740,  1.7849, -0.8635],
        [ 1.4783, -0.5967,  0.9172],
        [ 0.7989,  0.6343, -0.2419]])


In [7]:
print(x.size())

torch.Size([5, 3])
